package com.example.pomodoro.ui

/**
 * Material Symbols Rounded 图标码位表。
 *
 * 与网页 index.html 使用的同名图标完全一致（同一字体、同一 FILL/wght/GRAD/opsz 设置），
 * 字体已子集化到 composeResources/font/material_symbols_rounded.ttf。
 *
 * 用法：Text(SYMBOLS["timer"].orEmpty(), fontFamily = AppFonts.symbols, fontSize = 24.sp)
 */
val SYMBOLS: Map<String, String> = mapOf(
    "add" to "\uE145",
    "add_circle_outline" to "\uE990",
    "arrow_back" to "\uE5C4",
    "arrow_drop_down" to "\uE5C5",
    "arrow_forward" to "\uE5C8",
    "bar_chart" to "\uE26B",
    "celebration" to "\uEA65",
    "check" to "\uE668",
    "check_circle" to "\uF0BE",
    "checklist" to "\uE6B1",
    "checklist_rtl" to "\uE6B3",
    "chevron_left" to "\uE5CB",
    "chevron_right" to "\uE5CC",
    "close" to "\uE5CD",
    "code" to "\uE86F",
    "coffee" to "\uEFEF",
    "content_copy" to "\uE14D",
    "dark_mode" to "\uE51C",
    "delete" to "\uE92E",
    "done" to "\uE876",
    "done_all" to "\uE877",
    "download" to "\uF090",
    "drag_handle" to "\uE25D",
    "drag_indicator" to "\uE945",
    "eco" to "\uEA35",
    "edit" to "\uF097",
    "error" to "\uF8B6",
    "expand_less" to "\uE5CE",
    "expand_more" to "\uE5CF",
    "favorite" to "\uE87E",
    "filter_list" to "\uE152",
    "fullscreen" to "\uE5D0",
    "help" to "\uE8FD",
    "horizontal_rule" to "\uF108",
    "hourglass_bottom" to "\uEA5C",
    "image" to "\uE3F4",
    "info" to "\uE88E",
    "language" to "\uEA07",
    "light_mode" to "\uE518",
    "lightbulb" to "\uE90F",
    "link" to "\uE250",
    "list" to "\uE896",
    "monitoring" to "\uF190",
    "more_horiz" to "\uE5D3",
    "music_note" to "\uE405",
    "notification_add" to "\uE399",
    "notifications" to "\uE7F5",
    "notifications_active" to "\uE7F7",
    "open_in_new" to "\uE89E",
    "palette" to "\uE40A",
    "pause" to "\uE034",
    "picture_in_picture" to "\uE8AA",
    "play_arrow" to "\uE037",
    "play_circle" to "\uE1C4",
    "psychology" to "\uEA4A",
    "refresh" to "\uE5D5",
    "remove" to "\uE15B",
    "remove_circle" to "\uF08F",
    "repeat" to "\uE040",
    "replay" to "\uE042",
    "schedule" to "\uEFD6",
    "self_improvement" to "\uEA78",
    "settings" to "\uE8B8",
    "shuffle" to "\uE043",
    "skip_next" to "\uE044",
    "sort" to "\uE164",
    "star" to "\uF09A",
    "swipe_vertical" to "\uEB51",
    "sync" to "\uE627",
    "timer" to "\uE425",
    "toggle_on" to "\uE9F6",
    "tune" to "\uE429",
    "upload" to "\uF09B",
    "visibility" to "\uE8F4",
    "visibility_off" to "\uE8F5",
    "volume_up" to "\uE050",
    "warning" to "\uF083",
)
