[versions]
agp = "9.1.0"
kotlin = "2.4.10"
compose-multiplatform = "1.12.0"
androidx-activity = "1.10.1"
miuix = "0.8.8"
kotlinx-datetime = "0.7.1"

[libraries]
androidx-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
miuix-ui = { module = "top.yukonga.miuix.kmp:miuix", version.ref = "miuix" }
miuix-icons = { module = "top.yukonga.miuix.kmp:miuix-icons", version.ref = "miuix" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
android-application = { id = "com.android.application", version.ref = "agp" }
